### ISSUE TITLE
When trying to import t212 csv it shows the same error with all symbols

### ISSUE THREAD

**Issue by GerardPolloRebozado** [dickwolff/Export-To-Ghostfolio#101]
getSecurity(): No match found for symbol KO, trying by name Coca-Cola
[d]             getSymbolsByQuery(): An error ocurred while retrieving summary for KO. Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.. Skipping..
[d]             getSymbolsByQuery(): An error ocurred while retrieving summary for COKE. Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.. Skipping..
[d]             getSymbolsByQuery(): An error ocurred while retrieving summary for CCEP. Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.. Skipping..
[d]             getSymbolsByQuery(): An error ocurred while retrieving summary for CCC3.DU. Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.. Skipping..
[d]             getSymbolsByQuery(): An error ocurred while retrieving summary for KOF. Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.. Skipping..
[d]             getSymbolsByQuery(): Quote 'Coca-Cola' has no symbol at Yahoo Finance undefined. Skipping..
[d]             getSymbolsByQuery(): Quote 'Coca-Cola' has no symbol at Yahoo Finance undefined. Skipping..
[i] No result found for dividend action for US1912161007 with currency USD! Please add this manually..
[d]             getSymbolsByQuery(): An error ocurred while retrieving summary for ADP. Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.. Skipping..
[d]     getSecurity(): Found 0 matches by ISIN US0530151036

**Comment by dickwolff** [comment]
Which version of the tool are you using? This is an error that occured with an outdated version of our yahoo-finance2 dependency.

**Comment by GerardPolloRebozado** [comment]
that was the issue, I made git pull but not npm i
