### ISSUE TITLE
Revolut Support

### ISSUE THREAD

**Issue by SodaSyrup** [dickwolff/Export-To-Ghostfolio#107]
Hello, a support for Revoluts Investing Service would be nice. I know you can Export statements in the app itself, i also found this:
https://developer.revolut.com/docs/guides/accept-payments/tutorials/create-csv-reports

**Comment by dickwolff** [comment]
Thanks for the request! An example export containing the likes of buy/sale (with transaction fees if applicable) would be nice! If there are interests, dividends and such it would  be nice if those are included as well. 

When I receive the sample export I can create a first draft for you!

**Comment by dickwolff** [comment]
The absolute best thing would be an example CSV. You could change the amounts if you would be more comfortable with that.

**Comment by dickwolff** [comment]
That would not be a problem I think!

**Comment by dickwolff** [comment]
Sorry for the late response, I've been busy so I couldn't work on this. Thanks for the details. I will work on it this week and let you know if I have a first version for you to test!

**Comment by dickwolff** [comment]
Disregard my latest, I've gone ahead and build it just now ;-)

Can you test this for me? You can download [this](https://hub.docker.com/layers/dickwolff/export-to-ghostfolio/0.19.0-beta/images/sha256-473e1e76c62ea0aae4ebf9e84f201c841b93767047f4daf178c43dbbd7b17e44) Docker image. Please let me know if there are any issues that need fixing!

Also, when you're satistief, could you provide me with some instructions that I could put in the [README](https://github.com/dickwolff/Export-To-Ghostfolio/blob/main/README.md)?

**Comment by dickwolff** [comment]
@SodaSyrup Could you take a look at this and test it for me? Thanks!
