### ISSUE TITLE
Schwab unsupported records

### ISSUE THREAD

**Issue by rahulsh1** [dickwolff/Export-To-Ghostfolio#121]
Exported the CSV from Schwab and during the import, following records were missing the `type` field in the converted json.

CSV Records:

    "09/06/2024","ADR Mgmt Fee","IBN","ICICI BANK LTD FSPONSORED ADR 1 ADR REPS 2 ORD SHS","","","","-$0.50"
    "09/06/2024","Foreign Tax Paid","IBN","ICICI BANK LTD FSPONSORED ADR 1 ADR REPS 2 ORD SHS","","","","-$1.30"
    "07/15/2024 as of 07/12/2024","Stock Split","AVGO","BROADCOM INC","9","$170.067","",""

These get converted to JSON (formatted):

    {
      "accountId": "test",
      "comment": "",
      "fee": 0,
      "quantity": 0,
      "unitPrice": 0,
      "currency": "USD",
      "dataSource": "YAHOO",
      "date": "2024-09-06T00:00:00+00:00",
      "symbol": "IBN"
    },
    {
      "accountId": "test",
      "comment": "",
      "fee": 0,
      "quantity": 0,
      "unitPrice": 0,
      "currency": "USD",
      "dataSource": "YAHOO",
      "date": "2024-09-06T00:00:00+00:00",
      "symbol": "IBN"
    },
    {
      "accountId": "test",
      "comment": "",
      "fee": 0,
      "quantity": 9,
      "unitPrice": 170.067,
      "currency": "USD",
      "dataSource": "YAHOO",
      "date": "2024-07-15T00:00:00+00:00",
      "symbol": "AVGO"
    }

Note the missing `type` for each of these that prevents Ghostfolio from importing the json.
The rest seem to be fine. Thanks for making it so easy to add records.

**Comment by rahulsh1** [comment]
Wondering if you have any ideas on how Stock splits should be handled?

**Comment by dickwolff** [comment]
Thanks for reporting this. 

I think the management fees one is pretty straightforward, I can add that to the list of fee records.

Regarding the other two, are there other records that relate to those? As in: do those 2 records come standalone or are there more records that go with it? Regarding the stock split, for example, there could be a buy and/or sell record associated (I’m not familiar with Schwab myself so I’m just guessing 😉)

**Comment by rahulsh1** [comment]
Both the `ADR Mgmt Fee` and `Foreign Tax Paid` should fall under the fee record for ADRs. 

The split one is linked to another BUY transaction for the same symbol at an earlier date. 

    "06/13/2024","Buy","AVGO","BROADCOM INC","1","$1680.00","","-$1680.00"

The "Stock Split" record should apply to all transactions for the same symbol before this date (07/15/2024). With a `10:1` split as in this case for `AVGO`, the purchase price for the above record should be 1/10th of the price mentioned ($168). 
The split record covers the rest of quantity and buy price (9 shares at $170.067). 
HTH

**Comment by dickwolff** [comment]
Got all of these covered! Will be part of the next release.
