### ISSUE TITLE
Crash on unkown record types from trading212

### ISSUE THREAD

**Issue by deej81** [dickwolff/Export-To-Ghostfolio#14]
import crashes on record types of currency conversion and interest on cash

**Comment by dickwolff** [comment]
Thanks for your contribution! 

I will take a look at your PR when I get back from holiday

**Comment by dickwolff** [comment]
This is a nice improvement over the current implementation. As I commented on the PR, I have merged the changes and will make some improvements on the converter in #13 in which I will also take inspiration of your change.
