### ISSUE TITLE
reduce wait time on yahoo for repeated ISIN numbers

### ISSUE THREAD

**Issue by Joren-vanGoethem** [dickwolff/Export-To-Ghostfolio#21]
add a local file or cache to save the found isin numbers to speed up conversion
cache only stays for the current run, file stays across runs

what do you think @dickwolff ?

**Comment by dickwolff** [comment]
Great suggestion. I have a cache of sorts in the current service but that does not work across multiple runs. Will look into that for sure!

**Comment by dickwolff** [comment]
There was an issue with the TypSxcript Map not being correctly processed and saved in cache. This is now resolved.

However there are now issues with retrieving symbols that are linked to the current "old" DEGIRO converter. This has to do with the way the current converter works with parsing records, and conflicting currencies. When #18  is merged, these issues should be resolved I believe.

**Comment by dickwolff** [comment]
I have made the final changes to the cache in #22 , which should work now :-)
