### ISSUE TITLE
JSON not working if language does not match - date must be a valid ISO 8601 date string

### ISSUE THREAD

**Issue by dascgit** [dickwolff/Export-To-Ghostfolio#3]
Hi

Since I can not respond to the old issue (https://github.com/dickwolff/DEGIRO-to-Ghostfolio/issues/1) I opened a new one here. It looks better now, but now something with the date doesn`t work.

Image:
![image](https://github.com/dickwolff/Export-To-Ghostfolio/assets/125344779/c8e7364e-132e-4c4e-afdc-fbdcd2cc4ac9)

Example JSON output
`{
  "accountId": "9b6128be-97ff-4d53-a7b0-ef58413e307f",
  "comment": "",
  "fee": 0.29,
  "quantity": 1,
  "type": "DIVIDEND",
  "unitPrice": 1.93,
  "currency": "USD",
  "dataSource": "YAHOO",
  "date": "Invalid Date",
  "symbol": "A"
}`

**Comment by dickwolff** [comment]
Thanks! I will try to look in to it later this week!

**Comment by dascgit** [comment]
Updated Ghostfolio now the Import works fine.

**Comment by dickwolff** [comment]
Great! So only the date issue remains?
