### ISSUE TITLE
No error indication when debugging errors raised when processing lines.

### ISSUE THREAD

**Issue by Sonlis** [dickwolff/Export-To-Ghostfolio#35]
When running the conversion, I had an error that would display as such: 
```
[e] An error ocurred while trying to retrieve symbol US7561091049 (line 8)! 
```
After 1 hour of debugging, and printing the correct error, it was because of this: 
```
[Error: EACCES: permission denied, mkdir '/var/e2g-cache'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/var/e2g-cache'
} 
```
It would be an improvement to display the user why did it fail, instead of just letting them know an error has risen.
I would propose to add the error to the console log message here: https://github.com/dickwolff/Export-To-Ghostfolio/blob/51834f42dc2102f53f2a1461c5be1e6ff0ec7ef1/src/converters/abstractconverter.ts#L107
Such as:
```
    protected logQueryError(query: string, index: number, err: string) {

        let message = `\n[e] An error ocurred while trying to retrieve {query} (line ${index + 2}): ${err}.\n`;
```
And add the error when calling the `logQueryError` function for each converter, but for example here: https://github.com/dickwolff/Export-To-Ghostfolio/blob/51834f42dc2102f53f2a1461c5be1e6ff0ec7ef1/src/converters/degiroConverterV2.ts#L101.

Or modify the ErrorCallbackFunction from just returning `process.exit(99)` to log the error before exiting.

**Comment by dickwolff** [comment]
Thanks for reporting this! Did you by chance run the tool manually/locally? (so not the Docker version)

I have error reporting built in, but I saw the manual runner does not write it to the logs whereas the Docker version does. 

I will add the error reporting to the manual runner later this week and report back!

**Comment by Sonlis** [comment]
Indeed, it was by running the tool locally. And yes, the docker version displays the error here: https://github.com/dickwolff/Export-To-Ghostfolio/blob/51834f42dc2102f53f2a1461c5be1e6ff0ec7ef1/src/watcher.ts#L75

I added the same kind of display to the manual run, in a PR soon to be created :D

**Comment by dickwolff** [comment]
Merged! Thanks for your contribution!
