### ISSUE TITLE
[Degiro exporter v2] Error parsing Dutch transaction export from degiro.nl

### ISSUE THREAD

**Issue by claesmathias** [dickwolff/Export-To-Ghostfolio#44]
claesmathias@rpifive:~/export-to-ghostfolio$ docker logs -f export-to-ghostfolio 

> export-to-ghostfolio@1.0.0 watch
> ts-node ./src/watcher.ts

[i] Watching /var/e2g-input (using polling)..
[i] Found Transactions.csv!
[i] Determined the file type to be of kind 'degiro-v2' (overidden by environment variable).
[i] Restored 0 ISIN-symbol pairs and 0 symbols from cache..
[i] Processing file using DeGiro converter (V2 Beta)
[i] NOTE: You are running a converter that is currently in beta.
[i] If you have any issues, please report them on GitHub. Many thanks!
[e] An error ocurred while processing.
[e] Error details: Error: An error ocurred while parsing!
[e] Moving file to output..
[Transactions.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/14731656/Transactions.csv)

**Comment by dickwolff** [comment]
Thanks for reporting this! I'm sending this message to acknowledge the bug, but as I'm currently occupied with work I'm not able to work on the tool. I expect to have more time in about 2 weeks time and will look into it then!

**Comment by dxmekch** [comment]
@claesmathias you need to export the Accounts.csv not the Transactions.csv most likely

Headers should be as follows:
`Datum,Tijd,Valutadatum,Product,ISIN,Omschrijving,FX,Mutatie,,Saldo,,Order Id`

**Comment by claesmathias** [comment]
Tested image dickwolff/export-to-ghostfolio:0.7.4-beta with export from Account Overview instead of Transaction Overview and works. Thx!
