### ISSUE TITLE
No arm linux/arm64 docker image

### ISSUE THREAD

**Issue by claesmathias** [dickwolff/Export-To-Ghostfolio#45]
Kindly requesting to publish arm docker images on docker hub, to avoid local build or republish.

**Comment by dickwolff** [comment]
Thanks for reporting this! I'm sending this message to acknowledge the bug, but as I'm currently occupied with work I'm not able to work on the tool. I expect to have more time in about 2 weeks time and will look into it then!

**Comment by claesmathias** [comment]
Yes, thx a lot! I will give it a try tomorrow.

**Comment by claesmathias** [comment]
Works as expected, thx! No need to build it anymore myself.

**Comment by dickwolff** [comment]
Thanks for confirming! I have merged the changes and am closing this issue.
