### ISSUE TITLE
Only Fees being processed in Docker

### ISSUE THREAD

**Issue by mikaelheidrich** [dickwolff/Export-To-Ghostfolio#52]
Hi Dick,

I'm back after a long time! great work on the converter in the mean time! Congrats.

I've been playing with the docker instance. Using both docker and docker compose. 
When trying to process Finpension and Swissquote, the only data converted is fees and interest but no equities.

let me know what you may need to track this down.
Mikael

**Comment by mikaelheidrich** [comment]
Hi Dick,

Yeah, I found it weird too. same behaviour both executing from docker and docker-compose. here is the finpension csv I was trying to convert.
[transaktions_report.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/15042548/transaktions_report.csv)

thanks!

**Comment by dickwolff** [comment]
Thanks. Will look into it later this weekend. 

To verify, the Docker logs do state the Finpension converter is being used?

**Comment by mikaelheidrich** [comment]
Yes, now and again it gets identified as Rabobank and then ultimately it runs as finpension.

**Comment by dickwolff** [comment]
Thanks! Will check tomorrow if I can find a solution!

**Comment by dickwolff** [comment]
@mikaelheidrich I took the `transaktions_report.csv` file and ran `npm run start finpension`. It gave me the following result: [ghostfolio-finpension.json](https://github.com/dickwolff/Export-To-Ghostfolio/files/15049357/ghostfolio-finpension.json). At first glance it does look allright.

I did however see a lot of errors retrieving symbols from Yahoo Finance. After running `npm install` those went away. There was a new version of the Yahoo Finance library available which I had not installed locally. Could you maybe try if this resolves the issue when running locally?

**Comment by mikaelheidrich** [comment]
Hi Dick,
I pulled the new docker image and re-ran the transactions_repot.csv and it seems to  work now.

**Comment by dickwolff** [comment]
Thanks for your suggestion. I will add the current timestamp to the filename!

**Comment by dickwolff** [comment]
Now available in [0.8.3](https://hub.docker.com/layers/dickwolff/export-to-ghostfolio/0.8.3/images/sha256-e431f903bcf18cc5079da8bb56f6a95335e995752cc2796a26bff28c653c9c48)

**Comment by dickwolff** [comment]
Closing since original issue is solved. 

Should you have any other request or issues, please open a new issue!
