### ISSUE TITLE
Swissquote and finpension as brokers

### ISSUE THREAD

**Issue by mikaelheidrich** [dickwolff/Export-To-Ghostfolio#7]
Any chance of adding Swissquote and finpension as importable brokerages?

**Comment by dickwolff** [comment]
If you can provide me with example exports I can take a look at it!

**Comment by mikaelheidrich** [comment]
Hey thanks for the quick response. attached are an example of finpension transaction exported csv and another from swissquote.


thanks!!

**Comment by mikaelheidrich** [comment]
Are these CSVs ok or do you need more examples?

**Comment by dickwolff** [comment]
Sorry, haven't had time to look at it yet. After a quick glance just now I think the finpension export will work, but I need more transactions for Swissquote (different kinds, for example buy/sell are missing).

**Comment by mikaelheidrich** [comment]
Ok, I’ll upload a more elaborate cab later today. No worries. Appreciate you taking the time to check it out! :)

**Comment by mikaelheidrich** [comment]
Heya, heres a more elaborate swissquote example.
[swissquote_transaction-2.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/13203515/swissquote_transaction-2.csv)

**Comment by dickwolff** [comment]
This could work. When I have some time I will try and work this out!

**Comment by dickwolff** [comment]
I have added a Finpension converter [here](https://github.com/dickwolff/Export-To-Ghostfolio/tree/feature/Add-Finpension-Converter). Can you try and verify if it works for you? The file you provided is converted succesfully and as far as I can see all looks good.

Please let me know if you have any findings. If all is good, can you provide me with step-by-step instructions how to make a Finpension export (like [here](https://github.com/dickwolff/Export-To-Ghostfolio#download-transaction-export)), so I can add it to the readme?

When I find some time later this week I will work on the Swissquote converter!

**Comment by dickwolff** [comment]
@mikaelheidrich I also added the Swissquote converter to the same branch. 

Can you take a look at them and verify if they process your exports? Both CSV's you provided seem to be converted OK and are importable to Ghostfolio.

Can you also provide export instructions for Swissquote (as well as for Finpension), so I can add those to the manual? Thanks!

**Comment by mikaelheidrich** [comment]
Hi Dick,I had a quick look at finpension, looks good at first glance. I take a look at the Swissquote over the weekend and will provide instructions on how to download the csv for both. Thanks a lot!MikaelOn 24 Nov 2023, at 09:59, Dick Wolff ***@***.***> wrote:﻿
@mikaelheidrich I also added the Swissquote converter to the same branch.
Can you take a look at them and verify if they process your exports? Both CSV's you provided seem to be converted OK and are importable to Ghostfolio.
Can you also provide export instructions for Swissquote (as well as for Finpension), so I can add those to the manual? Thanks!

**Comment by dickwolff** [comment]
I had this same error on Yahoo Finance this morning, I believe this is because Yahoo Finance is rate limiting you because their api was requested too many times within the hour.

As for the discontinued ETF, it isn’t placed in the JSON which you import in Ghostfolio?

**Comment by mikaelheidrich** [comment]
No the discontinued ETF does not appear in the json file after being processed. I have retried the swissquote csv’s with less entries 20 instead of 79. but no matter the amount of requests same error pops up. I can run 5 different Finpension accounts all with 100 plus activities without error. Seems something specific to the swissquote process.

thanks again for the help. 

Mikael

ill try and get some instructions and screen shots for how to download the transaction csv’s in the coming days.

**Comment by dickwolff** [comment]
Okay, I will try and look into the Swissquote error later this week and get back to you when I find something!

**Comment by mikaelheidrich** [comment]
Hi Dick,

For Finpension. 
Login to your Finpension account. Select your portfolio from the landing page. Then to the right of the screen select “Transactions”, on the following page to the right notice “transaction report (CSV-file)” and click to email or click to download locally.

For Swissquote Switzerland.
Login to the Swissquote account. From the bar menu click on “Transactions”. Select the desired time period as well as types and then select the “export CSV” button to the right. 



hope this helps. 

Thanks Dick, looking forward to getting Swissquote working 100%!

Mikael

**Comment by dickwolff** [comment]
Thanks for the instructions! I have added them to the readme file.

As to the issue you describe with Swissquote. I have run the export you provided in this thread (swissquote_transaction-2.csv) without any issue just now. Can you please check wether you still have issues at this time? If so, can you provide me with a (partial) export of the record(s) that give you an error? That way I can analyse the issue and get to a fix.

**Comment by mikaelheidrich** [comment]
Hi Dick,

I have attached a csv with the transactions that crash the converter. It looks like it's the forex debit ones that generate the error. In the screen shot also see the no result found notices. how do I fix those ones?

thank for the help. Going to be a slick little app…
Mikael

**Comment by dickwolff** [comment]
They were records without an ISIN, so no wonder they break :-)

I have added them to the skip list. Can you verify one last time before I merge these changes?

**Comment by mikaelheidrich** [comment]
Hi Dick, exporter runs now with no crashing. So I have gone through three years of transactions and I have merged all the remainng troublesome exports from my broker into one csv. 

[sample-swissquote-export.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/13622817/sample-swissquote-export.csv)


The following is noteworthy.

-VEUD Dividend is mis identified as veurl.as where as the VEUD buy or sell is correctly identified as VEUD.L
-Custody Fees should be identified as Fees
-ORFN is the discontinued ETF, I can enter those manually i think
- in 2022 the sell transaction IAAA, CORP and IGIL throw a no result found as it seems to be looking for CHF instead of USD, other transactions exactly the same in other years of these same ETFs worked no problem.
- WENS gets identified as WENS.AS in EUR instead of WENS in USD
- VWRL dividend gets identified as WWRD.AS, Eur instead of USD.
- ETH should be identified as Ethereum Crypto Currency

I could also be noted that, after deselecting wrong imports in Ghostfolio and subsequently deleting succesful transactions from the cvs and then re-runing the export tool, some of the faulty exports where then exported correctly. That is to say, trimming down the csv and reruning it sometimes fixed some of the faulty exports.

hope this helps,

Mikael

**Comment by dickwolff** [comment]
Thanks for your detailed analysis. I will try to take a look this weekend and come back to you.

**Comment by dickwolff** [comment]
@mikaelheidrich The file you attached seems to be empty

**Comment by mikaelheidrich** [comment]
strange, lets try this one:

[sample-swissquote-export-merged.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/13623678/sample-swissquote-export-merged.csv)

**Comment by dickwolff** [comment]
I added custody fee support. Will now look at the file you sent and check your analysis.

**Comment by dickwolff** [comment]
@mikaelheidrich Did you manaually merge the files? The tool does not process is because the column count does not match. The header has 15 columns, but there are many rows with only 13 columns.

**Comment by dickwolff** [comment]
Pushed some more changes. 

Regarding your analysis, my thoughts below:

- VEUD is matched to VEUR.AS as that is the only match found while searching by ISIN (when you enter IE00B945VV12 in Yahoo Finance you only get VEUR.AS. The tool does not continue to look for another symbol because the currency matches (your dividend is paid in EUR and VEUR.AS is EUR. 
- Custody fees are added. Please check if the values are mapped correctly.
- I see the records for IAAA, CORP, etc. have another currency attached in the row. This value wasn't used (it used currency from the last column). I have now added a control to use netAmountCurrency if present, otherwise currency. The tool now finds matches.
- WENS now matches in USD
- VRWL now matches in USD
- There is no way for the tool to determine ETH is the cryptocurrency. Trying something with combining names (like ETH-USD) is probably going to break something somewhere else, though.

**Comment by dickwolff** [comment]
Merged changes into main branch. If any issues persist, please open a new issue.

**Comment by mikaelheidrich** [comment]
Heya Dick,Sorry to not have responded. Holidays busy busy around here. I’ll take a look at things after the new year and touch base. Thanks a bunch!Happy holiday abs happy new year.On 28 Dec 2023, at 11:32, Dick Wolff ***@***.***> wrote:﻿
Closed #7 as completed via #10.
