### ISSUE TITLE
Include BUX csv template

### ISSUE THREAD

**Issue by huub66** [dickwolff/Export-To-Ghostfolio#77]
Hi, great tool, thanks for developing! Would it be possible to include the BUX CSV template to the tool?

[bux_csv_template.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/15480576/bux_csv_template.csv)

**Comment by dickwolff** [comment]
Thanks for the request and the sample CSV. I will try and work on it this weekend and get back to you!

**Comment by dickwolff** [comment]
I still have to add test coverage, but [here is a first draft](https://hub.docker.com/layers/dickwolff/export-to-ghostfolio/0.14.0-beta/images/sha256-21a10a038637ea828dfb886a0cce7fecfa6fd63663c3107963445bcf827d573c?context=explore) of the BUX converter for you to try. Can you test this and let me know if everything works as expected? 

Also, can you provide me with the export instructions so I can add them to the readme? Please check the current export instructions in the readme if you need inspiration 😅. Thanks!

**Comment by huub66** [comment]
Not yet successful in conversion, see below command and result;

```
docker run --rm -v /ghostfolio-export/in-folder:/var/tmp/e2g-input -v /ghostfolio-export/out-folder:/var/tmp/e2g-output --env GHOSTFOLIO_ACCOUNT_ID=e1c71dd6-5726-44de-a143-0cf0e6ba3d73 dickwolff/export-to-ghostfolio:0.14.0-beta

> export-to-ghostfolio@0.14.0 watch
> tsx ./src/watcher.ts

[i] Watching /var/tmp/e2g-input..
[i] Found ._bux_transaction_history.csv!
[i] Determined the file type to be of kind 'bux'.
[i] Starting Export to Ghostfolio v0.14.0
[i] Found bux_transaction_history.csv!
[i] Determined the file type to be of kind 'bux'.
[i] Starting Export to Ghostfolio v0.14.0
[i] Restored 0 ISIN-symbol pairs and 0 symbols from cache..
[i] Processing file using Bux converter
[i] Restored 0 ISIN-symbol pairs and 0 symbols from cache..
[i] Processing file using Bux converter
[e] An error ocurred while processing.
[e] Error details: Error: An error ocurred while parsing!
[e] Moving file to output..
[i] Stop container as usePolling is set to false..
```

**Comment by dickwolff** [comment]
Hmm, that error message is not really helpful. I’ll need to improve that. 

The error occurs when parsing the file. Something with either the headers or the contents. Will try and add some more detailed logging so you can try again. I will get back to you and let you know when the logging is added.

**Comment by dickwolff** [comment]
I have added more logging in the converter (was separate PR but merged the changes).

Can you pull [this](https://hub.docker.com/layers/dickwolff/export-to-ghostfolio/0.14.0-beta/images/sha256-70559c1f4ec2fa9d2ab08932adfbda9e65fd4e79ca9f78ebd405b1a1e77473af?context=explore) image and try again so the CSV parse issue will show? Thanks!

**Comment by dickwolff** [comment]
While adding tests I found there was an issue with the `yahoo-finance2` dependency. I have updated the dependency and now it seems to work again. I have pushed a new version of `0.14.0-beta` to Docker Hub.

**Comment by huub66** [comment]
Thanks for following up on this, conversion is now running smooth! Output file however is generated incorrectly, the timestamp of the conversion time is used for all activities while it should be the timestamp per activity from the csv file. 
-

**Comment by huub66** [comment]
Thanks for following up on this, conversion is now running smooth! Output file however is generated incorrectly, the timestamp of the conversion time is used for all activities while it should be the timestamp per activity from the csv file.

**Comment by dickwolff** [comment]
I see the timestamp mapping did not read the correct value. I have fixed that now and the sample export converts with corresponding timestamps! A new `0.14.0-beta` is now available!

**Comment by huub66** [comment]
Works! 

One suggestion though; would it be possible to name platform related fees an interest as "Bux Interest" or "Bux Fee". In the current ways these cost are generated with a string as name which looks quite confusing in the UI. Not sure if ghostfolio is offering a better way to prevent this, being new to that application as well :)

**Comment by dickwolff** [comment]
Great suggestion, I've added this just now.

Can you help me with the export instructions, so I can put them in de README file? Thanks a lot!

**Comment by huub66** [comment]
Thanks! 
Will create some instructions tomorrow.

**Comment by huub66** [comment]
Noticed you had created some instructions already, just a small remark; you can retrieve transaction history 3x per day instead 3x per month. Herewith some screens to support your instructions;

![1170-2314-max](https://github.com/dickwolff/Export-To-Ghostfolio/assets/68535665/43d4c3da-ae1f-4ec3-80df-d7a2fa8461e8)

![1170-2092-max](https://github.com/dickwolff/Export-To-Ghostfolio/assets/68535665/faf4fac3-567a-4a77-bb30-ecb10ad8602d)

**Comment by dickwolff** [comment]
Yes, i took them from the BUX support website. I thought I read there is was 3 times per month. Will change that, thanks for the tip!
