### ISSUE TITLE
DeGiro conversion failing

### ISSUE THREAD

**Issue by huub66** [dickwolff/Export-To-Ghostfolio#78]
When using the docker instance I get the following error when trying to convert a freshly downloaded DeGiro transaction list;

> export-to-ghostfolio@1.0.0 watch
> tsx ./src/watcher.ts

[i] Watching /var/tmp/e2g-input..
[i] Found ._Transactions.csv!
[i] Determined the file type to be of kind 'freetrade'.
[i] Found Transactions.csv!
[i] Determined the file type to be of kind 'degiro'.
[i] Restored 0 ISIN-symbol pairs and 0 symbols from cache..
[i] Processing file using Freetrade converter
[i] Restored 0 ISIN-symbol pairs and 0 symbols from cache..
[i] Processing file using DeGiro converter
[e] An error ocurred while processing.
[e] Error details: Error: An error ocurred while parsing!
=> undefined
[e] Moving file to output..
[i] Stop container as usePolling is set to false..
npm notice 
npm notice New minor version of npm available! 10.5.2 -> 10.8.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.0>
npm notice Run `npm install -g npm@10.8.0` to update!
npm notice 

file format:
[Transactions.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/15482449/Transactions.csv)

Could you support understanding this issue?

**Comment by dickwolff** [comment]
Thanks for reporting. I will check it tomorrow!

**Comment by dickwolff** [comment]
I have added more detailed logging that shows what's wrong with a CSV file for future reference. 

In your case, I see you have exported data from the `Transactions` tab. The tool does not support that format. You'll need to export the `Account statement` tab data. Reason being the `Transaction` tab does not contain dividends, fees, etc. 

![image](https://github.com/dickwolff/Export-To-Ghostfolio/assets/5620002/171ecb7b-fb9c-4e55-8335-14e0fcd8522e)
