### ISSUE TITLE
Convert Schwab csv to import to GhostFolio?

### ISSUE THREAD

**Issue by DCPDad** [dickwolff/Export-To-Ghostfolio#8]
Hello!

I appreciate your work, and I was curious if you ever had a request to convert a CSV from Schwab to be able to import into Ghostfolio.

Many thx-
Dan

**Comment by dickwolff** [comment]
If you can provide an example export of Schwab with the likes of buy/sell/dividend orders, I can take a look at it!

**Comment by DCPDad** [comment]
Wow!
Thank you So much for your response!

I’d appreciate your thoughts on converting the Schwab test CSV to be able
to import it into Ghostfolio.

I am in the process of testing Ghostfolio to see if it fits my needs.

Many, MANY thx!
Dan




Dan Pennington

*Pennington Family Office*
*cell: (949) 500-0975*
*fax: (949) 304-6349*

*email: ***@***.****
*webpage*
*: Dan.PenningtonFamily.org <https://dan.penningtonfamily.org/>*
Click here <https://nextcloud.danlikesthis.com/s/DCPDad_Upload> to upload
files to me securely.
The content of this email is confidential and intended for the recipient
specified in the message only. It is strictly forbidden to share any part
of this message with any third party without the written consent of the
sender. If you received this message by mistake, please reply to this
message and follow with its deletion so that we can ensure such an error
does not occur in the future.

**Comment by DCPDad** [comment]
Please let me know if I can provide anything else to help.

Thank you!

Dan

**Comment by dickwolff** [comment]
For some reason I don't see the attachement you sent me. Can you try again?

**Comment by DCPDad** [comment]
Oh no!

Yes, of course. I’m sorry about that!
Dan

**Comment by DCPDad** [comment]
Hello-

I am not sure if you received the attachment (not showing here, but it was in the email). Please let me know if you'd rather I upload it directly to github.

**Comment by dickwolff** [comment]
I just checked again but there isn't an attachment added to the email I received from GitHub. 

I think the easiest wat would be if you upload it here. I have some commitments this week but

**Comment by dickwolff** [comment]
Closes by accident

**Comment by DCPDad** [comment]
No problem, and whenever you get a chance to look at the attached, it
[Schwab Test.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/13326307/Schwab.Test.csv)
 would be great. No pressure.

**Comment by dickwolff** [comment]
@DCPDad I just downloaded the file to check the contents. Are these transactions or positions? Looks like the latter. To process an export, the file should contain buy/sell/dividend transactions. These can then be converted to Ghostfolio format and be imported.

**Comment by DCPDad** [comment]
Good question! They should be Transactions. BUT I have created another dummy CSV (attached) that might be clearer
[Schwab sample2.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/13326408/Schwab.sample2.csv)
?
I really appreciate your efforts on this.

**Comment by dickwolff** [comment]
That looks more like it! I'll notify you once I have something you can take a look at!

**Comment by dickwolff** [comment]
Hi @DCPDad!

I have created an exporter for Schwab. You can find it [here](https://github.com/dickwolff/Export-To-Ghostfolio/tree/feature/Add-Schwab-Converter). Would you be so kind to test it and give me feedback as to how it performs?

I have made some assumptions as to how records should be interpreted. As I'm European I'm not familiar with the the different dividend options there were present in the sample you provided. To summarize: I have interpreted `reinvest shares` as a BUY order (for Ghostfolio), and any other transaction (like `Qual Div` `Reinvest Dividend`, `Long Term Cap Gain`) I have categorized as a DIVIDEND for Ghostfolio. Please correct me if I have misinterpreted something so I can fix that!

If all is well, can you provide me with step-by-step instructions how to make a Schwab export (like [here](https://github.com/dickwolff/Export-To-Ghostfolio#download-transaction-export)), so I can add it to the readme? Thanks!

**Comment by DCPDad** [comment]
Thank you!

I will test this out. Please keep in mind, while I used to code many, many
years ago, I am not a coder.

Initial feedback:
As a first-timer, I had first to install VS Code on my Mac
After installing VS Code on my Mac, I also needed to install Node.js to
have npm available
After running “npm run start schwab” in the Terminal in VS Code, I received
the attached feedback and error messages

NO rush! Just enjoying the progress! Thank you so much Dick!
Dan




Dan Pennington

*Pennington Family Office*
*cell: (949) 500-0975*
*fax: (949) 304-6349*

*email: ***@***.****
*webpage*
*: Dan.PenningtonFamily.org <https://dan.penningtonfamily.org/>*
Click here <https://nextcloud.danlikesthis.com/s/DCPDad_Upload> to upload
files to me securely.
The content of this email is confidential and intended for the recipient
specified in the message only. It is strictly forbidden to share any part
of this message with any third party without the written consent of the
sender. If you received this message by mistake, please reply to this
message and follow with its deletion so that we can ensure such an error
does not occur in the future.

**Comment by DCPDad** [comment]
Sorry. I guess attachments dont work with github.

Here is the error message:

npm run start schwab > ***@***.*** start > nodemon
schwab [nodemon] 2.0.22 [nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/* [nodemon] watching extensions: ts,js
[nodemon] starting `ts-node ./src/index.ts schwab` Processing file using
Schwab converter TypeError: The "path" argument must be of type string or
an instance of Buffer or URL. Received undefined at Object.readFileSync
(node:fs:451:42) at SchwabConverter.processFile
(/Users/danpennington/Desktop/1-Ghostfolio
Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/src/converters/schwabConverter.ts:27:28)
at Object. (/Users/danpennington/Desktop/1-Ghostfolio
Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/src/index.ts:34:11)
at Module._compile (node:internal/modules/cjs/loader:1376:14) at
Module.m._compile (/Users/danpennington/Desktop/1-Ghostfolio
Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/node_modules/ts-node/src/index.ts:1618:23)
at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) at
Object.require.extensions. [as .ts]
(/Users/danpennington/Desktop/1-Ghostfolio
Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/node_modules/ts-node/src/index.ts:1621:12)
at Module.load (node:internal/modules/cjs/loader:1207:32) { code:
'ERR_INVALID_ARG_TYPE' } [nodemon] app crashed - waiting for file changes
before starting...

I'll look into my process of the env when I get back to my office — that
might be the issue. I did modify with account and parh but maybe it was
still sample...

Thx
Dan




Dan Pennington


Pennington Family Office
cell: (949) 500-0975
fax: (949) 304-6349
email: ***@***.***
webpage: Dan.PenningtonFamily.org

To upload a file to me: https://nextcloud.danlikesthis.com/s/DCPDad_Upload

The content of this email is confidential and intended for the recipient
specified in the message only. It is strictly forbidden to share any part
of this message with any third party without the written consent of the
sender. If you received this message by mistake, please reply to this
message and follow with its deletion so that we can ensure such an error
does not occur in the future.

**Comment by DCPDad** [comment]
Making headway! YAY!

It was “pilot error” - I had a typo on the path to my export - sorry!

It went through your program without error.

I do now, though get two errors for each ‘activity’ (0 through 139) when
trying to import:

activities.0.fee must not be less than 0

activities.0.fee must be a number conforming to the specified constraints

{
  "accountId": "7b657d8d-dc70-4dd2-8f9a-8b74d3a7c147",
  "comment": "",
  "fee": null,
  "quantity": 1.6531,
  "type": "BUY",
  "unitPrice": 420.1,
  "currency": "USD",
  "dataSource": "YAHOO",
  "date": "2023-11-01T00:00:00-07:00",
  "symbol": "SPY"
}



Thoughts?
MANY thx-
Dan




Dan Pennington

*Pennington Family Office*
*cell: (949) 500-0975*
*fax: (949) 304-6349*

*email: ***@***.****
*webpage*
*: Dan.PenningtonFamily.org <https://dan.penningtonfamily.org/>*
Click here <https://nextcloud.danlikesthis.com/s/DCPDad_Upload> to upload
files to me securely.
The content of this email is confidential and intended for the recipient
specified in the message only. It is strictly forbidden to share any part
of this message with any third party without the written consent of the
sender. If you received this message by mistake, please reply to this
message and follow with its deletion so that we can ensure such an error
does not occur in the future.

**Comment by DCPDad** [comment]
Wow - you are good!

Thank you!




Dan Pennington


Pennington Family Office
cell: (949) 500-0975
fax: (949) 304-6349
email: ***@***.***
webpage: Dan.PenningtonFamily.org

To upload a file to me: https://nextcloud.danlikesthis.com/s/DCPDad_Upload

The content of this email is confidential and intended for the recipient
specified in the message only. It is strictly forbidden to share any part
of this message with any third party without the written consent of the
sender. If you received this message by mistake, please reply to this
message and follow with its deletion so that we can ensure such an error
does not occur in the future.

**Comment by DCPDad** [comment]
Hello Dick!
Just checking in to see if you had a chance to look at the 'fee error'?
Thank you!

**Comment by dickwolff** [comment]
@DCPDad Did you have a chance to check if the tool works for you?

**Comment by DCPDad** [comment]
> @DCPDad Did you have a chance to check if the tool works for you?

I am hoping to test it this weekend!
Thank you for creating this.

**Comment by dickwolff** [comment]
Thanks, please let me know if you find anything!

For your information, I saw some issues with dividend records with Schwab, so I just fixed those. I also added support for fee records when importing to Ghostfolio. Could you verify if the resulting `Advisor Fee` records are imported correclty?

**Comment by DCPDad** [comment]
> Thanks, please let me know if you find anything!
> 
> For your information, I saw some issues with dividend records with Schwab, so I just fixed those. I also added support for fee records when importing to Ghostfolio. Could you verify if the resulting `Advisor Fee` records are imported correclty?

Thanks Dick.

I tried but didn;t get too far. I am sure it is "pilot error" as I am not very familiar with using VS Code. I received this error after typing npm run start schwab

> trading212-to-ghostfolio@1.0.0 start
> nodemon schwab

[nodemon] 3.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts,js
[nodemon] starting `ts-node ./src/index.ts schwab`
sh: ts-node: command not found
[nodemon] failed to start process, "ts-node ./src/index.ts" exec not found
[nodemon] Error
    at Bus.<anonymous> (/usr/local/lib/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (node:events:526:35)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nodemon/lib/monitor/run.js:199:11)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

**Comment by dickwolff** [comment]
Could you perhaps try to run `npm install` and then run the tool again?

**Comment by DCPDad** [comment]
Thank you! It appears to be processing!

I had to run sudo chown -R 501:20 "/Users/danpennington/.npm" then run npm install again.

Looking great! Now I can play with Ghostfolio a bit. I will report anything that looks unusual.

MANY many thx!

**Comment by DCPDad** [comment]
Question:
I'm not sure where the CUSIP that your converter or Ghostfolio come from, but it doesn't seem to recognize a US T-Bill I have in a new portfolio I was trying to convert.
The "Symbol" Schwab is exporting is: 912797HX8
Which is [https://www.treasurydirect.gov/instit/annceresult/press/preanre/2023/A_20230829_2.pdf](url)
No biggie as I don't have many T-Bills.

**Comment by dickwolff** [comment]
What CSV line is that at? 912797HX8 does not return a result when searching on Yahoo Finance.

**Comment by DCPDad** [comment]
> What CSV line is that at? 912797HX8 does not return a result when searching on Yahoo Finance.

Thanks for your help Dick!
912797HX8 is in a new CSV I just downloaded. No worries: since I only have a few T-Bills I will remove them from the CSV. Maybe Ghostfolio allows me to add them individually?

**Comment by dickwolff** [comment]
You can add records manually to Ghostfolio, but if Ghostfolio can find it, the tool should as well!

**Comment by DCPDad** [comment]
> You can add records manually to Ghostfolio, but if Ghostfolio can find it, the tool should as well!

Thomas suggested something similar:
"One possibility would be to record them manually as a "Valuable", meaning that it does not track the current market value, but the value appears at least in the net worth calculation." so I will try that.

I did have another error - it may have to do with Interest. Please see the attached sample file.

The error it threw was:
throw new ErrorClass(errorObj.description);
                          ^
BadRequestError: Missing required query parameter=q

Any ideas?

Many thx!
Dan
[Sample_Transactions.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/13628562/Sample_Transactions.csv)

**Comment by dickwolff** [comment]
That one is not processed correctly. I will add an Interest record (I just checked and Ghostfolio does support interest records).

**Comment by dickwolff** [comment]
@DCPDad I just added the interest processing, can you try if it works?

**Comment by DCPDad** [comment]
We are making great headway!

I haven't tried the import process on this new file yet, but I did see these messages after the conversion process:

 No result found for dividend action for SNAXX with currency USD! Please add this manuall.
[i]     No result found for buy action for QQQ with currency USD! Please add this manually..
[i]     No result found for sell action for SNAXX with currency USD! Please add this manually..
[i]     No result found for dividend action for SNAXX with currency USD! Please add this manuall.
[i]     No result found for sell action for SNAXX with currency USD! Please add this manually..
[i]     No result found for dividend action for SNAXX with currency USD! Please add this manuall.

Any thoughts?

Thx-
Dan

**Comment by dickwolff** [comment]
Thanks, will try to look into these issues later this week.

**Comment by DCPDad** [comment]
I hope your holidays have been peaceful and calm, Dick.

Have you had a chance to look into this?

Many thx!
Dan

**Comment by dickwolff** [comment]
It was very good, thanks for asking!

I have just pushed some changes which fix the date issues. 

As for the other messages you sent, I don't see those when I run the tool with the example export. Can you try to run it again with the latest code, and send me the records that fail if the issue persists? Thanks!

**Comment by DCPDad** [comment]
Glad you had a great holiday.

Thank you for your help.

I am getting this error when I try to run your new update:
Error: No converter provided (i.e. trading212, degiro)

Any thoughts?

**Comment by dickwolff** [comment]
Did you run it with the `schwab` command, like `npm run start schwab`?

**Comment by DCPDad** [comment]
Yes. I downloaded your latest, modified the .env, ran "npm install" and then ran "npm run start schwab".

**Comment by dickwolff** [comment]
One more check, you did run the code from [here](https://github.com/dickwolff/Export-To-Ghostfolio/tree/feature/Add-Schwab-Converter)?

**Comment by DCPDad** [comment]
My bad! Sorry about that -- I must have grabbed it from the production code! (It has been a while since I updated).

Progress!

I do now get three errors when trying to import into Ghostfolio:
activities.9.date must be a valid ISO 8601 date string
{
  "accountId": "<removed by me>",
  "comment": "",
  "fee": 0.02,
  "quantity": 1,
  "type": "INTEREST",
  "unitPrice": 0.02,
  "currency": "USD",
  "dataSource": "MANUAL",
  "date": "Invalid Date",
  "symbol": "BANK INT 082923-091523 SCHWAB BANK"

**Comment by dickwolff** [comment]
Ah yes, that's my bad! I forgot to put the US date conversion on interest records. Should be fixed now if you update again!

**Comment by DCPDad** [comment]
**WAHOOOO!
NO Errors!**

YAY! Now I will play with the more extensive set of data.

VERY cool and MANY thanks Dick!

**Comment by dickwolff** [comment]
That's great news! Please let me know how it goes and if you find any inconsistenties that need fixing. 

If all goes well, could you provide export instructions like [here](https://github.com/dickwolff/Export-To-Ghostfolio#download-transaction-export) so I can add those to the manual?

**Comment by DCPDad** [comment]
So far SO GOOD!

Here are the "instructions" -- I hope this helps!

Schwab
Login to your Schwab account. Go to “Accounts” then “History”. Select the account you want to download details from. Select the “Date Range” and select “Export” (csv). Save the file.
![screenshot-client schwab com-2023 12 28-12_07_22](https://github.com/dickwolff/Export-To-Ghostfolio/assets/8687743/3431ee76-276e-446e-80ea-d404cd81e588)

**Comment by dickwolff** [comment]
Great to hear it's working well! And thank you for the instructions, I will add those tomorrow!

**Comment by DCPDad** [comment]
I think I see a small problem (he says hopefully!).

In comparing the CSV import to what Ghostfolio has, maybe a comma got recognized wrong.

The CSV import has this line:
"09/08/2023","Sell","SNAXX","SCHWAB VALUE ADVANTAGE MONEY ULTRA","500,135","$1.00","","$500135.00"

The json export of activities has this for the same transaction:
    {
      "accountId": "<I removed this detail for posting>",
      "comment": null,
      "fee": 0,
      "quantity": 500,
      "type": "SELL",
      "unitPrice": 1,
      "currency": "USD",
      "dataSource": "YAHOO",
      "date": "2023-09-08T07:00:00.000Z",
      "symbol": "SNAXX"
    },

The Qty is off: 500 vs 500,135

I can supply you with more details (I wish there were a non-public way of sharing these with you) :/

**Comment by dickwolff** [comment]
That would be an US value parsing issue (since the usage of comma's and dots in numbers is different). 

I have changed some code and it now returns the following for me:
```
{
            "accountId": "aaaaaaaaaaaaaaaaaaaaaaaa",
            "comment": "",
            "fee": 0,
            "quantity": 500.135,
            "type": "SELL",
            "unitPrice": 100,
            "currency": "USD",
            "dataSource": "YAHOO",
            "date": "2023-09-08T00:00:00+02:00",
            "symbol": "SNAXX"
        },
```

Do these values match what you expect?

PS: I have committed the changes, so when you update the code you can try again yourself as well!

**Comment by DCPDad** [comment]
I really appreciate your help and truly feel we are SO close -- thank you!

I downloaded the latest and get this new error:
TSError: ⨯ Unable to compile TypeScript:
src/converters/schwabConverter.ts:12:14 - error TS18052: Non-abstract class 'SchwabConverter' does not implement all abstract members of 'AbstractConverter'

**Comment by dickwolff** [comment]
Should be fixed now (however I fixed this on my phone so I haven’t tested it 🤞🏼). If it doesn’t work now, I’ll fix it for you tomorrow!

I did some code cleanup this morning but forgot to reflect those changes in the Schwab code.

**Comment by DCPDad** [comment]
Hmmm. Looking forward to you taking a look tomorrow. Again, I appreciate your help.

Most recent build got me this error:
npm run start schwab

> trading212-to-ghostfolio@1.0.0 start
> nodemon schwab

[nodemon] 3.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts,js
[nodemon] starting `ts-node ./src/index.ts schwab`
[i] Processing file using Schwab converter
/Users/<removed by me>/Desktop/1-Ghostfolio Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/src/index.ts:42
        throw new Error("No converter provided (i.e. trading212, degiro)");
              ^
Error: No converter provided (i.e. trading212, degiro)
    at Object.<anonymous> (/Users/<removed by me>/Desktop/1-Ghostfolio Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/src/index.ts:42:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (/Users/<removed by me>/Desktop/1-Ghostfolio Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/<removed by me>/Desktop/1-Ghostfolio Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at phase4 (/Users/<removed by me>/Desktop/1-Ghostfolio Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/Users/<removed by me>/Desktop/1-Ghostfolio Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/node_modules/ts-node/src/bin.ts:95:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dickwolff** [comment]
Did you test [these](https://github.com/dickwolff/Export-To-Ghostfolio/tree/feature/Add-Schwab-Converter) changes?

**Comment by DCPDad** [comment]
Ha - no I think I used the one we had been using. Sorry about that - it looks like you have integrated into the main one which is awesome!
I will test and report.
Thank you and Happy New Year!

**Comment by DCPDad** [comment]
Just downloaded it from your primary source (the one you just now sent), and I am getting the same/similar error:

npm run start schwab

> trading212-to-ghostfolio@1.0.0 start
> nodemon schwab

[nodemon] 3.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts,js
[nodemon] starting `ts-node ./src/index.ts schwab`
[i] Processing file using Schwab converter
/Users/xxx/Desktop/1-Ghostfolio Test/Export-To-Ghostfolio-feature-Add-Schwab-Converter/src/index.ts:42
        throw new Error("No converter provided (i.e. trading212, degiro)");

**Comment by dickwolff** [comment]
The one I sent should be the work in progress version of Schwab. I haven't merged it to primary since I want to be sure it works to your satisfaction before I make it available for the public 😄

If that one does not work however, I currently dont know what it could be. I will look into it tomorrow and come back to you.

**Comment by dickwolff** [comment]
@DCPDad I found the issue and have resolved it just now. Whenever you have time, please try again.

**Comment by DCPDad** [comment]
NO errors during run! Yay!

But it looks like something similar is happening to 'fees':
Input file shows:
10/10/2023	Advisor Fee		MGMTFEE TO ADVISOR				-$2862.87

Output file shows:
MGMTFEE TO ADVISOR | Fee | 10/10/2023 | 1.00 | 286,287.00 | 286,287.00 | 286,287.00 | USD | RESNN
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by DCPDad** [comment]
Opps - same with Cash Dividend. It should be $1431.87, but after the conversion, it is 143187.00

**Comment by dickwolff** [comment]
Looks like I accidentally added some code that completely broke the amounts. I removed that and when I run it myself, I get logical values.

**Comment by dickwolff** [comment]
I'm planning to add some automated testing early next year that automatically validates these kind of errors and warns me in advance. This also will help me validate other fixes as I don't have to do it all manually every time 😉

**Comment by DCPDad** [comment]
Ha - thanks and trying some automation is a great idea!!

I honestly do appreciate your back-and-forth with me. I feel we are getting quite close!

Please let me know when you want an amateur to test again :)

**Comment by dickwolff** [comment]
You can run your test again now!

**Comment by DCPDad** [comment]
CLOSER!

Looks like the "Sell" calculation might be the only one still broken:
09/08/2023	Sell	SNAXX	SCHWAB VALUE ADVANTAGE MONEY ULTRA	500,135	$1.00		$500135.00
shows as:
The Charles Schwab Family of Funds - Schwab Value Advantage Money FundSNAXX | Sell | 09/08/2023 | 500.00 | 1.00 | 0.00 | 500.00 | USD | RESNN
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by dickwolff** [comment]
That was an issue with numbers > 999, should also be fixed now. That specific record you mentioned now has a quantity of 500135.

**Comment by DCPDad** [comment]
Ohhhh - the numbers look valid!

Now to test, but WOW! Thank you so much for your quick turn-arounds!

**Comment by dickwolff** [comment]
@DCPDad Have you had a chance to look at the results? I would like to promote these changes to the main branch so other users can also use the tool with Schwab 🙂.

**Comment by dickwolff** [comment]
Due to inactivity I have merged the Schwab converter to the main branch. Should there be any issues left, please create an issue so that we can look into resolving it.
