### ISSUE TITLE
Error when processing DEGIRO file due to Currency Exchange operation

### ISSUE THREAD

**Issue by CristianAbrante** [dickwolff/Export-To-Ghostfolio#82]
When operating in DEGIRO in multiple currencies (In my case EUR and USD), there is an entry on the export file that refers to registering the exchange rate used for the transaction (more information [here](https://www.degiro.es/helpdesk/tarifas/existen-costes-por-operar-en-otra-divisa) in Spanish 🙏🏼 ).

This causes an error on the export.

<img width="974" alt="Screenshot 2024-07-02 at 20 08 10" src="https://github.com/dickwolff/Export-To-Ghostfolio/assets/32130345/06cad4f3-7baa-48b3-8063-52d8a0f6f805">

## How to reproduce
 Using this file:
[Account-2.csv](https://github.com/user-attachments/files/16071917/Account-2.csv)

## Possible fix

Skip this line? As it is apparently only a registry of the type of currency  exchange? 🤔

**Comment by dickwolff** [comment]
Thanks for reporting this. Skipping the line you mention seems like the best thing to do. I will fix this later this week and get back to you!

**Comment by dickwolff** [comment]
I have added the records in question to the ignore list. Can you try it out by pulling the [beta image](https://hub.docker.com/layers/dickwolff/export-to-ghostfolio/0.14.1-beta/images/sha256-e1e9d3cf69f57759daa5aeee785575fa2373050af091af89a7179364cc2e78db)?

**Comment by dickwolff** [comment]
PR closed. Should there be any other issue, please let me know!
