### ISSUE TITLE
Symbol mapping

### ISSUE THREAD

**Issue by Trefex** [dickwolff/Export-To-Ghostfolio#86]
I think currently you take the first symbol we can find in Yahoo ?

Would it be possible to somehow specify the symbol to be used?

Eg in my case it used SPY5.L but I would have preferred SPY5.DE.

Many thanks
T

**Comment by dickwolff** [comment]
Hi there!

The Security Service looks for the first match based on the currency that is related to the transaction. In most cases this works.

I have previously added a setting called `DEGIRO_PREFERED_EXCHANGE_POSTFIX`, which was added for DEGIRO but can also be used for other brokers. When you put `.DE` in this, it will try to take symbols that match that postfix. Is this something that could suit your needs? 

I think it's not a good idea to maintain a list of specific symbols. This could open pandora's box and cause all kinds of other problems.

**Comment by Trefex** [comment]
I am not sure, what I am sure is that for SPY5 it was completely wrong.

Eg SPY5.L is in USD but SPY5.DE is in EUR, even though the share class is in USD.

Maybe what I am saying doesn't make any sense

**Comment by dickwolff** [comment]
I think I get what you mean. I have had this issue with other ETF's as wel (V3AL, SMH). However I have not found a way to make this consistently work and it has been a rabbit hole I currently don't want to get back in to 🙈
