### ISSUE TITLE
Swissquote cash balance

### ISSUE THREAD

**Issue by Trefex** [dickwolff/Export-To-Ghostfolio#87]
Hi,

Do you know / see a way to also get cash balance into SQ?

Many thanks
T

**Comment by dickwolff** [comment]
Hi, 

Do you mean you want to get cash positions into Ghostfolio?

**Comment by Trefex** [comment]
Yes, since each account can have both cash balance (eg how much money you have available for investing or for currency holding?), I think the account should then reflect the full situation, eg assets including cash.

For instance, I use another plugin for IBKR that updates the cash balance + traders.

Same would go for Trade Republic etc.

**Comment by dickwolff** [comment]
So am I correct in understanding you would like a sync method between SQ and Ghostfolio, updating the cash balance within Ghostfolio to reflect your cash balance inside SQ? Just so I understand correct what you mean.

**Comment by Trefex** [comment]
Yeah including assets of course. Do you think that would make sense?

**Comment by dickwolff** [comment]
I know Ghostfolio has a setting to update cash balance (which I believe would then subtract of or add money to the balance when you add an activity). I'm not sure if this balance is for your whole Ghostfolio instance or of a specific account. 

I could look into the API of Ghostfolio and check if that cash feature could be enabled with the upload functionality, and then make it a setting to enable this in the tool. 

If that would not work, then it goes beyond the scope of what my goal with this tool is. It is supposed to be a "simple" tool to convert exports and then (automatically) import into Ghostfolio. Managing the cash balance goes beyond that.

**Comment by dickwolff** [comment]
Update: I've added `updateCashBalance` to the tool and the setting `GHOSTFOLIO_UPDATE_CASH`. When you set this to `true`, then it will update the cash balance inside Ghostfolio.

I think this requires to you set your initial balance and then it should automatically update the balance when you do new transactions.

You can test it with the latest image.

**Comment by Trefex** [comment]
This is already nice but it does not reflect the actual cash balance on SQ side. Eg I am putting new money in there, then this new cash balance will not be reflected in Ghostfolio.

Or did my import not work properly ?

**Comment by Trefex** [comment]
Eg there is a type in the source export from SQ like this:

```08-07-2024 13:22:47;00000000;Payment;;;;1.0;8000.00;0.00;0.00;8000.00;8307.15;EUR```

Those get ignored and not put into Ghostfolio.

**Comment by dickwolff** [comment]
No, your import was successful. Cash transfers are ignored by this tool. This is not specific to SQ, it is ignored at all converters and is by design.

**Comment by Trefex** [comment]
Ok so that was my question :)
