### ISSUE TITLE
Failure to deal with empty response from Yahoo Finance in combination with no symbol being present. 

### ISSUE THREAD

**Issue by sandervankasteel** [dickwolff/Export-To-Ghostfolio#9]
Hi,

Yesterday I've setup Ghostfolio, found your project and I tried to use this project to import my DeGiro transactions. 

However, in my DeGiro export contains the ISIN, `US00165C1045`. US00165C1045 is AMC, but the Yahoo Finance response is an empty array on the `quotes` element. So the converter it tries to rely on the symbol but the DeGiro export doesn't contain symbols for that line and thus subsequently fails.

**The CSV line on which the convert fails:** 
`01-02-2021,15:39,01-02-2021,AMC ENTERTAINMENT HOLD,US00165C1045,Valuta Debitering,1.2108,USD,-16.70,USD,0.00,43a88697-7358-4389-9440-d8aa6db536ce` 

**Yahoo finance response**
```
{
  explains: [],
  count: 0,
  quotes: [],
  news: [],
  nav: [],
  lists: [],
  researchReports: [],
  screenerFieldResults: [],
  totalTime: 23,
  timeTakenForQuotes: 415,
  timeTakenForNews: 0,
  timeTakenForAlgowatchlist: 400,
  timeTakenForPredefinedScreener: 400,
  timeTakenForCrunchbase: 400,
  timeTakenForNav: 400,
  timeTakenForResearchReports: 0,
  timeTakenForScreenerField: 0,
  timeTakenForCulturalAssets: 0
}
```

*Stacktrace*
```
TypeError: Cannot read properties of undefined (reading 'symbol')
    at YahooFinanceService.<anonymous> (/home/sander/tmp/Export-To-Ghostfolio/src/yahooFinanceService.ts:77:33)
    at Generator.next (<anonymous>)
    at fulfilled (/home/sander/tmp/Export-To-Ghostfolio/src/yahooFinanceService.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/home/sander/tmp/Export-To-Ghostfolio/src/yahooFinanceService.ts:77
            symbol = symbols[0].symbol.split(".")[0];
                                ^
TypeError: Cannot read properties of undefined (reading 'symbol')
    at YahooFinanceService.<anonymous> (/home/sander/tmp/Export-To-Ghostfolio/src/yahooFinanceService.ts:77:33)
    at Generator.next (<anonymous>)
    at fulfilled (/home/sander/tmp/Export-To-Ghostfolio/src/yahooFinanceService.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by dickwolff** [comment]
Thanks for reporting this. When I have some time I will look into this!

**Comment by sandervankasteel** [comment]
Thank you for looking into this! Just one gotcha, the line numbers in the stacktrace are off by 2 lines because I added some debugging to see why it failed and on which of the lines in the CSV file.

**Comment by dickwolff** [comment]
I have added some checks so the tool doesn't break when no symbols are found. I also added the `Product name` from the DEGIRO export to the Yahoo Finance search, and that way (in this case) AMC is found by name. See the code [here](https://github.com/dickwolff/Export-To-Ghostfolio/tree/feature/DEGIRO-Provide-Productname). 

Can you test if this resolves your issue? Thanks!

**Comment by sandervankasteel** [comment]
Hey @dickwolff I tried your changes, yes this partially solved my issue... But now it breaks on the following CSV lines;

```
01-08-2023,10:03,01-08-2023,ISHARES NASDAQ US BIOTECHNOLOGY ETF,IE00BYXG2H39,DEGIRO Transactiekosten en/of kosten van derden,,EUR,-1.00,EUR,5.54,4c29dd81-bb01-40fa-8dda-aae3d05dae79
01-08-2023,10:03,01-08-2023,ISHARES NASDAQ US BIOTECHNOLOGY ETF,IE00BYXG2H39,"Verkoop 1 @ 5,416 EUR",,EUR,5.42,EUR,6.54,4c29dd81-bb01-40fa-8dda-aae3d05dae79
25-07-2023,14:31,25-07-2023,ISHARES KOREA,IE00B0M63391,DEGIRO Transactiekosten en/of kosten van derden,,EUR,-1.00,EUR,44.92,d4f45240-d763-4b95-8590-2ba158d38207
25-07-2023,14:31,25-07-2023,ISHARES KOREA,IE00B0M63391,"Koop 1 @ 42,53 EUR",,EUR,-42.53,EUR,45.92,d4f45240-d763-4b95-8590-2ba158d38207
```
With the following error:
```
█████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 11% | ETA 176s | Duration: 18s | 107/901/home/sander/tmp/Export-To-Ghostfolio/src/converters/degiroConverter.ts:165                                                                                  
              result.activities[result.activities.length - 1].symbol = security.symbol;                                                                                                                                                       
                                                                                ^                                                                                                                                                             
TypeError: Cannot read properties of null (reading 'symbol')    
```

What happens is that the Yahoo Finance search returns nothing (ie. it cannot find anything)

```
getSecurity(): No initial match found, trying by symbol IDKO
getSecurity(): No match found for symbol IDKO, trying by name ISHARES KOREA
No result found for BUY action for IE00B0M63391 with currency EUR! Please add this manually..
```

But the deGiro converter still tries to add it to it's `result.activities` array and there it also tries to access it's symbol (which it doesn't has). 

So I tried to locally fix this, and what I've done is added an optional chaining (`.?`) on line 187 and 165,
`result.activities[result.activities.length - 1].symbol = security?.symbol;` and after that I get JSON file!

**Comment by sandervankasteel** [comment]
> Looks like it only found the transaction fees line but not the actual buy/sell line. They are both in the export?

I am seeing some buy and sell lines, but should those buy/sell lines be before or after the fee line?

**Comment by dickwolff** [comment]
Usually, buy/sell records are preceded by transaction fee records, like below:

```
15-12-2022,16:55,15-12-2022,VICI PROPERTIES INC. C,US9256521090,DEGIRO Transactiekosten en/of kosten van derden,,EUR,"-1,00",EUR,"31,98",5925d76b-eb36-46e3-b017-a61a6d03c3e7
15-12-2022,16:55,15-12-2022,VICI PROPERTIES INC. C,US9256521090,"Koop 1 @ 33,9 USD",,USD,"-33,90",USD,"-33,90",5925d76b-eb36-46e3-b017-a61a6d03c3e7
```

The tool looks for a buy/sell records after processing a transaction fee line. Given your error below:
``` 
{
  "accountId": "47ad8e74-9c2e-476e-9cb0-776e8660dea1",
  "comment": "txfees",
  "fee": 2,
  "quantity": 0,
  "unitPrice": 0,
  "currency": "EUR",
  "dataSource": "YAHOO",
  "date": "2020-04-21T09:05:00+02:00",
  "symbol": "VUSA.AS"
}
```

This means the tool has read a transaction fee line for VUSA, and then expects a buy/sell record (with that information it can "complete" the records).

**Comment by dickwolff** [comment]
Closing because no response was given. If the issue still persists, please reply so I can reopen the issue.
