### ISSUE TITLE
all stocks give an error only the fee's gets ready to upload

### ISSUE THREAD

**Issue by asterix778** [dickwolff/Export-To-Ghostfolio#91]
when i run the npm run start degiro with my file in it it says at all stocks "x with currency USD! please add this manually with currency EUR" 
this is the same for EUR stocks.

is there a way to fix this ?

i tried changing these lines:
XTB_ACCOUNT_CURRENCY = "EUR"
XTB_ACCOUNT_CURRENCY = "USD"
but that didn't help

**Comment by dickwolff** [comment]
When you run the DEGIRO converter, it will look for the currency inside your export file. This usually works for finding the correct match. Which specific securities give you trouble? Maybe you can provide me with a partial export, so I can look into it.

Fyi, setting the `XTB_ACCOUNT_CURRENCY` variables does not work with DEGIRO, as this is a XTB specific setting.

**Comment by asterix778** [comment]
Al stocks give this error.
Might it be a problem that the csv file contains the stock price in usd and the total kost is in euro?
Im going to give it a shot to disable the setting you said and remove the euro currency on the stocks where it has been payed in usd.
Thx for your responds!

**Comment by dickwolff** [comment]
If you buy a stock, the local currency is represented in the DEGIRO export. So if you buy GOOG, which is USD, the export should have USD. 

Could you maybe send me the export part that gives you troubles? That allows me to look into it better. Thanks!

**Comment by asterix778** [comment]
I tried the following i removed alot of columns and the message changed to:
[i] Starting Export to Ghostfolio v0.16.0
[i] Restored 0 ISIN-symbol pairs and 0 symbols from cache..
[i] Processing file using DeGiro converter
[e] An error ocurred while processing.
[e] Error: An error ocurred while parsing! Details: Invalid Record Length: columns length is 12, got 5 on line 2

these are the rows i left in:
Datum	        ISIN	                      FX	Mutatie	
19-07-2024	US22788C1053		USD	-310.85

the original file is the following with an example:

Datum	Tijd	Product	ISIN	Beurs	Uitvoeringsplaats	Aantal	Koers		Lokale waarde		Waarde		Wisselkoers	Transactiekosten en/of		Totaal		Order ID
17-07-2024	15:36	MICROSOFT CORPORATION	US5949181045	NDQ	ARCX	-1	443	USD	443	USD	404.83	EUR	1.0943	-2	EUR	402.83	EUR	dd60652f-eaf6-4ba5-8b77

with this i get the first error and the one below
[e] Error: An error ocurred while parsing! Details: Invalid Record Length: columns length is 12, got 19 on line 2

hope this helped if you need more info or other information let me know

**Comment by dickwolff** [comment]
Thanks for reporting. I will download an export of my own and check it. Your error indicates it’s something with your export, as the tool expects 12 or so columns and your export for some reason has 19.

**Comment by dickwolff** [comment]
I see, you've used the Transactions.cvs file. The tool used the Account.csv file (next tab). 

![image](https://github.com/user-attachments/assets/74270f1a-ea6b-402f-82da-0c602f8d1711)

For now, I'll add a warning for this in the tool, stating to use the correct export. For the future, I'll look into adding support for the Transactions.csv as well.

**Comment by dickwolff** [comment]
Closing this issue due to not supporting this format (yet). As stated, I will put it on the backlog.
